# -*- coding: utf-8 -*-
"""Salinan dari Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNkkX70pCMT3HuwOzfQC1B2vIsO8Wu3k
"""

import streamlit as st
import numpy as np
import tensorflow as tf
from PIL import Image, ImageOps
import cv2

# Load model
model = tf.keras.models.load_model('mnist_model.h5')

st.title("MNIST Digit Classifier")
st.write("Gambar angka (0-9) di bawah ini!")

# Upload gambar
uploaded_file = st.file_uploader("Upload gambar angka (png/jpg)", type=["png", "jpg", "jpeg"])

if uploaded_file is not None:
    # Tampilkan gambar asli
    image = Image.open(uploaded_file).convert('L')  # Convert to grayscale
    st.image(image, caption='Gambar yang diupload', use_column_width=True)

    # Preprocess gambar (resize ke 28x28)
    image = ImageOps.invert(image)  # Balik warna: putih jadi hitam
    image = image.resize((28, 28))
    image_array = np.array(image)

    # Normalisasi
    image_array = image_array / 255.0

    # Bentuk input: (1, 28, 28, 1)
    image_array = image_array.reshape(1, 28, 28, 1)

    # Prediksi
    prediction = model.predict(image_array)
    predicted_class = np.argmax(prediction)

    st.write(f"Prediksi: **{predicted_clas_**